'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class adminislemler

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ayarlarbuton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ayarlarbuton As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cikisyap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cikisyap As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''silbuton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents silbuton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''kullaniciismientry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kullaniciismientry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''kullaniciadientry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kullaniciadientry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''kullanicisifreentry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kullanicisifreentry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''kulaniciekleBtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kulaniciekleBtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''uyarilabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uyarilabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Repeater1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Repeater1 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''duzenlenenitemId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents duzenlenenitemId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''adminyetkisivarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents adminyetkisivarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''arizaeklemevarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arizaeklemevarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''arizasilmevarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arizasilmevarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''arizaguncellemevarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents arizaguncellemevarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''ariasonuclandirmavarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ariasonuclandirmavarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''stokkartieklemevarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stokkartieklemevarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''stokgirisiyapmavarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stokgirisiyapmavarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''stokcikisiyapmavarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stokcikisiyapmavarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''sayaceklemevarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sayaceklemevarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''sayacsilmevarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sayacsilmevarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''sayacislemgirmevarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sayacislemgirmevarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''sayacguncellemevarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sayacguncellemevarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''periyodikbakimeklemevarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents periyodikbakimeklemevarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''periyodikbakimsilmevarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents periyodikbakimsilmevarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''periyodikbakimguncellemevarmi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents periyodikbakimguncellemevarmi As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''dosyakayitdeneme control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dosyakayitdeneme As Global.System.Web.UI.WebControls.Label
End Class
